services:
  mariadb:
    image: mariadb:10.11
    container_name: netflixpp-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: netflixpp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netflixpp-network

  cassandra:
    image: cassandra:4.1
    container_name: netflixpp-cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=NetflixPPCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - netflixpp-network

  app:
    build: .
    container_name: netflixpp-backend
    ports:
      - "8080:8080"
      - "9001:9001"  # Porta do P2P
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_DATABASE=netflixpp
      - MARIADB_USER=netflixpp
      - MARIADB_PASSWORD=netflixpp123
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_DATACENTER=dc1
      - CASSANDRA_KEYSPACE=netflixpp
    volumes:
      - ./storage:/app/storage
    depends_on:
      mariadb:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    networks:
      - netflixpp-network

volumes:
  mariadb_data:
  cassandra_data:

networks:
  netflixpp-network:
    driver: bridge